/*
Kopfsachen

Kopfsachen e. V. is an association for the promotion of young people's mental health. The goal is to teach the basics of mental health literacy in various educational formats.

API version: 1.0.2
Contact: mail@kopfsachen.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// SchemaAccessAndDataPortability struct for SchemaAccessAndDataPortability
type SchemaAccessAndDataPortability struct {
	Available *bool `json:"available,omitempty"`
	Description *string `json:"description,omitempty"`
	Url *string `json:"url,omitempty"`
	Email *string `json:"email,omitempty"`
	IdentificationEvidences []map[string]interface{} `json:"identificationEvidences,omitempty"`
	AdministrativeFee *SchemaAccessAndDataPortabilityAdministrativeFee `json:"administrativeFee,omitempty"`
	DataFormats []map[string]interface{} `json:"dataFormats,omitempty"`
}

// NewSchemaAccessAndDataPortability instantiates a new SchemaAccessAndDataPortability object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSchemaAccessAndDataPortability() *SchemaAccessAndDataPortability {
	this := SchemaAccessAndDataPortability{}
	return &this
}

// NewSchemaAccessAndDataPortabilityWithDefaults instantiates a new SchemaAccessAndDataPortability object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSchemaAccessAndDataPortabilityWithDefaults() *SchemaAccessAndDataPortability {
	this := SchemaAccessAndDataPortability{}
	return &this
}

// GetAvailable returns the Available field value if set, zero value otherwise.
func (o *SchemaAccessAndDataPortability) GetAvailable() bool {
	if o == nil || o.Available == nil {
		var ret bool
		return ret
	}
	return *o.Available
}

// GetAvailableOk returns a tuple with the Available field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaAccessAndDataPortability) GetAvailableOk() (*bool, bool) {
	if o == nil || o.Available == nil {
		return nil, false
	}
	return o.Available, true
}

// HasAvailable returns a boolean if a field has been set.
func (o *SchemaAccessAndDataPortability) HasAvailable() bool {
	if o != nil && o.Available != nil {
		return true
	}

	return false
}

// SetAvailable gets a reference to the given bool and assigns it to the Available field.
func (o *SchemaAccessAndDataPortability) SetAvailable(v bool) {
	o.Available = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *SchemaAccessAndDataPortability) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaAccessAndDataPortability) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *SchemaAccessAndDataPortability) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *SchemaAccessAndDataPortability) SetDescription(v string) {
	o.Description = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *SchemaAccessAndDataPortability) GetUrl() string {
	if o == nil || o.Url == nil {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaAccessAndDataPortability) GetUrlOk() (*string, bool) {
	if o == nil || o.Url == nil {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *SchemaAccessAndDataPortability) HasUrl() bool {
	if o != nil && o.Url != nil {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *SchemaAccessAndDataPortability) SetUrl(v string) {
	o.Url = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *SchemaAccessAndDataPortability) GetEmail() string {
	if o == nil || o.Email == nil {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaAccessAndDataPortability) GetEmailOk() (*string, bool) {
	if o == nil || o.Email == nil {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *SchemaAccessAndDataPortability) HasEmail() bool {
	if o != nil && o.Email != nil {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *SchemaAccessAndDataPortability) SetEmail(v string) {
	o.Email = &v
}

// GetIdentificationEvidences returns the IdentificationEvidences field value if set, zero value otherwise.
func (o *SchemaAccessAndDataPortability) GetIdentificationEvidences() []map[string]interface{} {
	if o == nil || o.IdentificationEvidences == nil {
		var ret []map[string]interface{}
		return ret
	}
	return o.IdentificationEvidences
}

// GetIdentificationEvidencesOk returns a tuple with the IdentificationEvidences field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaAccessAndDataPortability) GetIdentificationEvidencesOk() ([]map[string]interface{}, bool) {
	if o == nil || o.IdentificationEvidences == nil {
		return nil, false
	}
	return o.IdentificationEvidences, true
}

// HasIdentificationEvidences returns a boolean if a field has been set.
func (o *SchemaAccessAndDataPortability) HasIdentificationEvidences() bool {
	if o != nil && o.IdentificationEvidences != nil {
		return true
	}

	return false
}

// SetIdentificationEvidences gets a reference to the given []map[string]interface{} and assigns it to the IdentificationEvidences field.
func (o *SchemaAccessAndDataPortability) SetIdentificationEvidences(v []map[string]interface{}) {
	o.IdentificationEvidences = v
}

// GetAdministrativeFee returns the AdministrativeFee field value if set, zero value otherwise.
func (o *SchemaAccessAndDataPortability) GetAdministrativeFee() SchemaAccessAndDataPortabilityAdministrativeFee {
	if o == nil || o.AdministrativeFee == nil {
		var ret SchemaAccessAndDataPortabilityAdministrativeFee
		return ret
	}
	return *o.AdministrativeFee
}

// GetAdministrativeFeeOk returns a tuple with the AdministrativeFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaAccessAndDataPortability) GetAdministrativeFeeOk() (*SchemaAccessAndDataPortabilityAdministrativeFee, bool) {
	if o == nil || o.AdministrativeFee == nil {
		return nil, false
	}
	return o.AdministrativeFee, true
}

// HasAdministrativeFee returns a boolean if a field has been set.
func (o *SchemaAccessAndDataPortability) HasAdministrativeFee() bool {
	if o != nil && o.AdministrativeFee != nil {
		return true
	}

	return false
}

// SetAdministrativeFee gets a reference to the given SchemaAccessAndDataPortabilityAdministrativeFee and assigns it to the AdministrativeFee field.
func (o *SchemaAccessAndDataPortability) SetAdministrativeFee(v SchemaAccessAndDataPortabilityAdministrativeFee) {
	o.AdministrativeFee = &v
}

// GetDataFormats returns the DataFormats field value if set, zero value otherwise.
func (o *SchemaAccessAndDataPortability) GetDataFormats() []map[string]interface{} {
	if o == nil || o.DataFormats == nil {
		var ret []map[string]interface{}
		return ret
	}
	return o.DataFormats
}

// GetDataFormatsOk returns a tuple with the DataFormats field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaAccessAndDataPortability) GetDataFormatsOk() ([]map[string]interface{}, bool) {
	if o == nil || o.DataFormats == nil {
		return nil, false
	}
	return o.DataFormats, true
}

// HasDataFormats returns a boolean if a field has been set.
func (o *SchemaAccessAndDataPortability) HasDataFormats() bool {
	if o != nil && o.DataFormats != nil {
		return true
	}

	return false
}

// SetDataFormats gets a reference to the given []map[string]interface{} and assigns it to the DataFormats field.
func (o *SchemaAccessAndDataPortability) SetDataFormats(v []map[string]interface{}) {
	o.DataFormats = v
}

func (o SchemaAccessAndDataPortability) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Available != nil {
		toSerialize["available"] = o.Available
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Url != nil {
		toSerialize["url"] = o.Url
	}
	if o.Email != nil {
		toSerialize["email"] = o.Email
	}
	if o.IdentificationEvidences != nil {
		toSerialize["identificationEvidences"] = o.IdentificationEvidences
	}
	if o.AdministrativeFee != nil {
		toSerialize["administrativeFee"] = o.AdministrativeFee
	}
	if o.DataFormats != nil {
		toSerialize["dataFormats"] = o.DataFormats
	}
	return json.Marshal(toSerialize)
}

type NullableSchemaAccessAndDataPortability struct {
	value *SchemaAccessAndDataPortability
	isSet bool
}

func (v NullableSchemaAccessAndDataPortability) Get() *SchemaAccessAndDataPortability {
	return v.value
}

func (v *NullableSchemaAccessAndDataPortability) Set(val *SchemaAccessAndDataPortability) {
	v.value = val
	v.isSet = true
}

func (v NullableSchemaAccessAndDataPortability) IsSet() bool {
	return v.isSet
}

func (v *NullableSchemaAccessAndDataPortability) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSchemaAccessAndDataPortability(val *SchemaAccessAndDataPortability) *NullableSchemaAccessAndDataPortability {
	return &NullableSchemaAccessAndDataPortability{value: val, isSet: true}
}

func (v NullableSchemaAccessAndDataPortability) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSchemaAccessAndDataPortability) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


