/*
Kopfsachen

Kopfsachen e. V. is an association for the promotion of young people's mental health. The goal is to teach the basics of mental health literacy in various educational formats.

API version: 1.0.2
Contact: mail@kopfsachen.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// ListOfWikiEntryHeaders struct for ListOfWikiEntryHeaders
type ListOfWikiEntryHeaders struct {
	EntryCount int32 `json:"entry_count"`
	Entries []WikiEntryHeader `json:"entries"`
}

// NewListOfWikiEntryHeaders instantiates a new ListOfWikiEntryHeaders object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListOfWikiEntryHeaders(entryCount int32, entries []WikiEntryHeader) *ListOfWikiEntryHeaders {
	this := ListOfWikiEntryHeaders{}
	this.EntryCount = entryCount
	this.Entries = entries
	return &this
}

// NewListOfWikiEntryHeadersWithDefaults instantiates a new ListOfWikiEntryHeaders object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListOfWikiEntryHeadersWithDefaults() *ListOfWikiEntryHeaders {
	this := ListOfWikiEntryHeaders{}
	return &this
}

// GetEntryCount returns the EntryCount field value
func (o *ListOfWikiEntryHeaders) GetEntryCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EntryCount
}

// GetEntryCountOk returns a tuple with the EntryCount field value
// and a boolean to check if the value has been set.
func (o *ListOfWikiEntryHeaders) GetEntryCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EntryCount, true
}

// SetEntryCount sets field value
func (o *ListOfWikiEntryHeaders) SetEntryCount(v int32) {
	o.EntryCount = v
}

// GetEntries returns the Entries field value
func (o *ListOfWikiEntryHeaders) GetEntries() []WikiEntryHeader {
	if o == nil {
		var ret []WikiEntryHeader
		return ret
	}

	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value
// and a boolean to check if the value has been set.
func (o *ListOfWikiEntryHeaders) GetEntriesOk() ([]WikiEntryHeader, bool) {
	if o == nil {
		return nil, false
	}
	return o.Entries, true
}

// SetEntries sets field value
func (o *ListOfWikiEntryHeaders) SetEntries(v []WikiEntryHeader) {
	o.Entries = v
}

func (o ListOfWikiEntryHeaders) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["entry_count"] = o.EntryCount
	}
	if true {
		toSerialize["entries"] = o.Entries
	}
	return json.Marshal(toSerialize)
}

type NullableListOfWikiEntryHeaders struct {
	value *ListOfWikiEntryHeaders
	isSet bool
}

func (v NullableListOfWikiEntryHeaders) Get() *ListOfWikiEntryHeaders {
	return v.value
}

func (v *NullableListOfWikiEntryHeaders) Set(val *ListOfWikiEntryHeaders) {
	v.value = val
	v.isSet = true
}

func (v NullableListOfWikiEntryHeaders) IsSet() bool {
	return v.isSet
}

func (v *NullableListOfWikiEntryHeaders) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListOfWikiEntryHeaders(val *ListOfWikiEntryHeaders) *NullableListOfWikiEntryHeaders {
	return &NullableListOfWikiEntryHeaders{value: val, isSet: true}
}

func (v NullableListOfWikiEntryHeaders) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListOfWikiEntryHeaders) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


