/*
Kopfsachen

Kopfsachen e. V. is an association for the promotion of young people's mental health. The goal is to teach the basics of mental health literacy in various educational formats.

API version: 1.0.2
Contact: mail@kopfsachen.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// BouncerLogoutApi403Response struct for BouncerLogoutApi403Response
type BouncerLogoutApi403Response struct {
	Error GenericError `json:"error"`
}

// NewBouncerLogoutApi403Response instantiates a new BouncerLogoutApi403Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBouncerLogoutApi403Response(error_ GenericError) *BouncerLogoutApi403Response {
	this := BouncerLogoutApi403Response{}
	this.Error = error_
	return &this
}

// NewBouncerLogoutApi403ResponseWithDefaults instantiates a new BouncerLogoutApi403Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBouncerLogoutApi403ResponseWithDefaults() *BouncerLogoutApi403Response {
	this := BouncerLogoutApi403Response{}
	return &this
}

// GetError returns the Error field value
func (o *BouncerLogoutApi403Response) GetError() GenericError {
	if o == nil {
		var ret GenericError
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *BouncerLogoutApi403Response) GetErrorOk() (*GenericError, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *BouncerLogoutApi403Response) SetError(v GenericError) {
	o.Error = v
}

func (o BouncerLogoutApi403Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["error"] = o.Error
	}
	return json.Marshal(toSerialize)
}

type NullableBouncerLogoutApi403Response struct {
	value *BouncerLogoutApi403Response
	isSet bool
}

func (v NullableBouncerLogoutApi403Response) Get() *BouncerLogoutApi403Response {
	return v.value
}

func (v *NullableBouncerLogoutApi403Response) Set(val *BouncerLogoutApi403Response) {
	v.value = val
	v.isSet = true
}

func (v NullableBouncerLogoutApi403Response) IsSet() bool {
	return v.isSet
}

func (v *NullableBouncerLogoutApi403Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBouncerLogoutApi403Response(val *BouncerLogoutApi403Response) *NullableBouncerLogoutApi403Response {
	return &NullableBouncerLogoutApi403Response{value: val, isSet: true}
}

func (v NullableBouncerLogoutApi403Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBouncerLogoutApi403Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


