/*
Kopfsachen

Kopfsachen e. V. is an association for the promotion of young people's mental health. The goal is to teach the basics of mental health literacy in various educational formats.

API version: 1.0.2
Contact: mail@kopfsachen.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// SafetyNetItemAllOf struct for SafetyNetItemAllOf
type SafetyNetItemAllOf struct {
	Id int32 `json:"id"`
}

// NewSafetyNetItemAllOf instantiates a new SafetyNetItemAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSafetyNetItemAllOf(id int32) *SafetyNetItemAllOf {
	this := SafetyNetItemAllOf{}
	this.Id = id
	return &this
}

// NewSafetyNetItemAllOfWithDefaults instantiates a new SafetyNetItemAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSafetyNetItemAllOfWithDefaults() *SafetyNetItemAllOf {
	this := SafetyNetItemAllOf{}
	return &this
}

// GetId returns the Id field value
func (o *SafetyNetItemAllOf) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SafetyNetItemAllOf) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SafetyNetItemAllOf) SetId(v int32) {
	o.Id = v
}

func (o SafetyNetItemAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableSafetyNetItemAllOf struct {
	value *SafetyNetItemAllOf
	isSet bool
}

func (v NullableSafetyNetItemAllOf) Get() *SafetyNetItemAllOf {
	return v.value
}

func (v *NullableSafetyNetItemAllOf) Set(val *SafetyNetItemAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableSafetyNetItemAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableSafetyNetItemAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSafetyNetItemAllOf(val *SafetyNetItemAllOf) *NullableSafetyNetItemAllOf {
	return &NullableSafetyNetItemAllOf{value: val, isSet: true}
}

func (v NullableSafetyNetItemAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSafetyNetItemAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


