/*
Kopfsachen

Kopfsachen e. V. is an association for the promotion of young people's mental health. The goal is to teach the basics of mental health literacy in various educational formats.

API version: 1.0.2
Contact: mail@kopfsachen.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// MotivatorValidationError struct for MotivatorValidationError
type MotivatorValidationError struct {
	Error string `json:"error"`
}

// NewMotivatorValidationError instantiates a new MotivatorValidationError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMotivatorValidationError(error_ string) *MotivatorValidationError {
	this := MotivatorValidationError{}
	this.Error = error_
	return &this
}

// NewMotivatorValidationErrorWithDefaults instantiates a new MotivatorValidationError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMotivatorValidationErrorWithDefaults() *MotivatorValidationError {
	this := MotivatorValidationError{}
	return &this
}

// GetError returns the Error field value
func (o *MotivatorValidationError) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *MotivatorValidationError) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *MotivatorValidationError) SetError(v string) {
	o.Error = v
}

func (o MotivatorValidationError) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["error"] = o.Error
	}
	return json.Marshal(toSerialize)
}

type NullableMotivatorValidationError struct {
	value *MotivatorValidationError
	isSet bool
}

func (v NullableMotivatorValidationError) Get() *MotivatorValidationError {
	return v.value
}

func (v *NullableMotivatorValidationError) Set(val *MotivatorValidationError) {
	v.value = val
	v.isSet = true
}

func (v NullableMotivatorValidationError) IsSet() bool {
	return v.isSet
}

func (v *NullableMotivatorValidationError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMotivatorValidationError(val *MotivatorValidationError) *NullableMotivatorValidationError {
	return &NullableMotivatorValidationError{value: val, isSet: true}
}

func (v NullableMotivatorValidationError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMotivatorValidationError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


