/*
Kopfsachen

Kopfsachen e. V. is an association for the promotion of young people's mental health. The goal is to teach the basics of mental health literacy in various educational formats.

API version: 1.0.2
Contact: mail@kopfsachen.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// SchemaDataDisclosedInnerStorageInnerTemporalInner struct for SchemaDataDisclosedInnerStorageInnerTemporalInner
type SchemaDataDisclosedInnerStorageInnerTemporalInner struct {
	Description string `json:"description"`
	Ttl string `json:"ttl"`
}

// NewSchemaDataDisclosedInnerStorageInnerTemporalInner instantiates a new SchemaDataDisclosedInnerStorageInnerTemporalInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSchemaDataDisclosedInnerStorageInnerTemporalInner(description string, ttl string) *SchemaDataDisclosedInnerStorageInnerTemporalInner {
	this := SchemaDataDisclosedInnerStorageInnerTemporalInner{}
	this.Description = description
	this.Ttl = ttl
	return &this
}

// NewSchemaDataDisclosedInnerStorageInnerTemporalInnerWithDefaults instantiates a new SchemaDataDisclosedInnerStorageInnerTemporalInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSchemaDataDisclosedInnerStorageInnerTemporalInnerWithDefaults() *SchemaDataDisclosedInnerStorageInnerTemporalInner {
	this := SchemaDataDisclosedInnerStorageInnerTemporalInner{}
	return &this
}

// GetDescription returns the Description field value
func (o *SchemaDataDisclosedInnerStorageInnerTemporalInner) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *SchemaDataDisclosedInnerStorageInnerTemporalInner) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *SchemaDataDisclosedInnerStorageInnerTemporalInner) SetDescription(v string) {
	o.Description = v
}

// GetTtl returns the Ttl field value
func (o *SchemaDataDisclosedInnerStorageInnerTemporalInner) GetTtl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ttl
}

// GetTtlOk returns a tuple with the Ttl field value
// and a boolean to check if the value has been set.
func (o *SchemaDataDisclosedInnerStorageInnerTemporalInner) GetTtlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ttl, true
}

// SetTtl sets field value
func (o *SchemaDataDisclosedInnerStorageInnerTemporalInner) SetTtl(v string) {
	o.Ttl = v
}

func (o SchemaDataDisclosedInnerStorageInnerTemporalInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["description"] = o.Description
	}
	if true {
		toSerialize["ttl"] = o.Ttl
	}
	return json.Marshal(toSerialize)
}

type NullableSchemaDataDisclosedInnerStorageInnerTemporalInner struct {
	value *SchemaDataDisclosedInnerStorageInnerTemporalInner
	isSet bool
}

func (v NullableSchemaDataDisclosedInnerStorageInnerTemporalInner) Get() *SchemaDataDisclosedInnerStorageInnerTemporalInner {
	return v.value
}

func (v *NullableSchemaDataDisclosedInnerStorageInnerTemporalInner) Set(val *SchemaDataDisclosedInnerStorageInnerTemporalInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSchemaDataDisclosedInnerStorageInnerTemporalInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSchemaDataDisclosedInnerStorageInnerTemporalInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSchemaDataDisclosedInnerStorageInnerTemporalInner(val *SchemaDataDisclosedInnerStorageInnerTemporalInner) *NullableSchemaDataDisclosedInnerStorageInnerTemporalInner {
	return &NullableSchemaDataDisclosedInnerStorageInnerTemporalInner{value: val, isSet: true}
}

func (v NullableSchemaDataDisclosedInnerStorageInnerTemporalInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSchemaDataDisclosedInnerStorageInnerTemporalInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


