/*
Kopfsachen

Kopfsachen e. V. is an association for the promotion of young people's mental health. The goal is to teach the basics of mental health literacy in various educational formats.

API version: 1.0.2
Contact: mail@kopfsachen.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// BrowserLogoutUrl struct for BrowserLogoutUrl
type BrowserLogoutUrl struct {
	// LogoutToken can be used to perform logout using AJAX.
	LogoutToken string `json:"logout_token"`
	// LogoutURL can be opened in a browser to sign the user out. format: uri
	LogoutUrl string `json:"logout_url"`
}

// NewBrowserLogoutUrl instantiates a new BrowserLogoutUrl object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBrowserLogoutUrl(logoutToken string, logoutUrl string) *BrowserLogoutUrl {
	this := BrowserLogoutUrl{}
	this.LogoutToken = logoutToken
	this.LogoutUrl = logoutUrl
	return &this
}

// NewBrowserLogoutUrlWithDefaults instantiates a new BrowserLogoutUrl object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBrowserLogoutUrlWithDefaults() *BrowserLogoutUrl {
	this := BrowserLogoutUrl{}
	return &this
}

// GetLogoutToken returns the LogoutToken field value
func (o *BrowserLogoutUrl) GetLogoutToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LogoutToken
}

// GetLogoutTokenOk returns a tuple with the LogoutToken field value
// and a boolean to check if the value has been set.
func (o *BrowserLogoutUrl) GetLogoutTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LogoutToken, true
}

// SetLogoutToken sets field value
func (o *BrowserLogoutUrl) SetLogoutToken(v string) {
	o.LogoutToken = v
}

// GetLogoutUrl returns the LogoutUrl field value
func (o *BrowserLogoutUrl) GetLogoutUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LogoutUrl
}

// GetLogoutUrlOk returns a tuple with the LogoutUrl field value
// and a boolean to check if the value has been set.
func (o *BrowserLogoutUrl) GetLogoutUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LogoutUrl, true
}

// SetLogoutUrl sets field value
func (o *BrowserLogoutUrl) SetLogoutUrl(v string) {
	o.LogoutUrl = v
}

func (o BrowserLogoutUrl) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["logout_token"] = o.LogoutToken
	}
	if true {
		toSerialize["logout_url"] = o.LogoutUrl
	}
	return json.Marshal(toSerialize)
}

type NullableBrowserLogoutUrl struct {
	value *BrowserLogoutUrl
	isSet bool
}

func (v NullableBrowserLogoutUrl) Get() *BrowserLogoutUrl {
	return v.value
}

func (v *NullableBrowserLogoutUrl) Set(val *BrowserLogoutUrl) {
	v.value = val
	v.isSet = true
}

func (v NullableBrowserLogoutUrl) IsSet() bool {
	return v.isSet
}

func (v *NullableBrowserLogoutUrl) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBrowserLogoutUrl(val *BrowserLogoutUrl) *NullableBrowserLogoutUrl {
	return &NullableBrowserLogoutUrl{value: val, isSet: true}
}

func (v NullableBrowserLogoutUrl) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBrowserLogoutUrl) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


