/*
Kopfsachen

Kopfsachen e. V. is an association for the promotion of young people's mental health. The goal is to teach the basics of mental health literacy in various educational formats.

API version: 1.0.2
Contact: mail@kopfsachen.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// WikiEntries struct for WikiEntries
type WikiEntries struct {
	Entries []WikiEntry `json:"entries,omitempty"`
}

// NewWikiEntries instantiates a new WikiEntries object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWikiEntries() *WikiEntries {
	this := WikiEntries{}
	return &this
}

// NewWikiEntriesWithDefaults instantiates a new WikiEntries object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWikiEntriesWithDefaults() *WikiEntries {
	this := WikiEntries{}
	return &this
}

// GetEntries returns the Entries field value if set, zero value otherwise.
func (o *WikiEntries) GetEntries() []WikiEntry {
	if o == nil || o.Entries == nil {
		var ret []WikiEntry
		return ret
	}
	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WikiEntries) GetEntriesOk() ([]WikiEntry, bool) {
	if o == nil || o.Entries == nil {
		return nil, false
	}
	return o.Entries, true
}

// HasEntries returns a boolean if a field has been set.
func (o *WikiEntries) HasEntries() bool {
	if o != nil && o.Entries != nil {
		return true
	}

	return false
}

// SetEntries gets a reference to the given []WikiEntry and assigns it to the Entries field.
func (o *WikiEntries) SetEntries(v []WikiEntry) {
	o.Entries = v
}

func (o WikiEntries) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Entries != nil {
		toSerialize["entries"] = o.Entries
	}
	return json.Marshal(toSerialize)
}

type NullableWikiEntries struct {
	value *WikiEntries
	isSet bool
}

func (v NullableWikiEntries) Get() *WikiEntries {
	return v.value
}

func (v *NullableWikiEntries) Set(val *WikiEntries) {
	v.value = val
	v.isSet = true
}

func (v NullableWikiEntries) IsSet() bool {
	return v.isSet
}

func (v *NullableWikiEntries) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWikiEntries(val *WikiEntries) *NullableWikiEntries {
	return &NullableWikiEntries{value: val, isSet: true}
}

func (v NullableWikiEntries) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWikiEntries) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


