/*
Kopfsachen

Kopfsachen e. V. is an association for the promotion of young people's mental health. The goal is to teach the basics of mental health literacy in various educational formats.

API version: 1.0.2
Contact: mail@kopfsachen.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// SchemaDataDisclosedInnerRecipientsInner struct for SchemaDataDisclosedInnerRecipientsInner
type SchemaDataDisclosedInnerRecipientsInner struct {
	Name *string `json:"name,omitempty"`
	Division *string `json:"division,omitempty"`
	Address *string `json:"address,omitempty"`
	Country *string `json:"country,omitempty"`
	Representative *SchemaDataDisclosedInnerRecipientsInnerRepresentative `json:"representative,omitempty"`
	Category *string `json:"category,omitempty"`
}

// NewSchemaDataDisclosedInnerRecipientsInner instantiates a new SchemaDataDisclosedInnerRecipientsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSchemaDataDisclosedInnerRecipientsInner() *SchemaDataDisclosedInnerRecipientsInner {
	this := SchemaDataDisclosedInnerRecipientsInner{}
	return &this
}

// NewSchemaDataDisclosedInnerRecipientsInnerWithDefaults instantiates a new SchemaDataDisclosedInnerRecipientsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSchemaDataDisclosedInnerRecipientsInnerWithDefaults() *SchemaDataDisclosedInnerRecipientsInner {
	this := SchemaDataDisclosedInnerRecipientsInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SchemaDataDisclosedInnerRecipientsInner) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaDataDisclosedInnerRecipientsInner) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SchemaDataDisclosedInnerRecipientsInner) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SchemaDataDisclosedInnerRecipientsInner) SetName(v string) {
	o.Name = &v
}

// GetDivision returns the Division field value if set, zero value otherwise.
func (o *SchemaDataDisclosedInnerRecipientsInner) GetDivision() string {
	if o == nil || o.Division == nil {
		var ret string
		return ret
	}
	return *o.Division
}

// GetDivisionOk returns a tuple with the Division field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaDataDisclosedInnerRecipientsInner) GetDivisionOk() (*string, bool) {
	if o == nil || o.Division == nil {
		return nil, false
	}
	return o.Division, true
}

// HasDivision returns a boolean if a field has been set.
func (o *SchemaDataDisclosedInnerRecipientsInner) HasDivision() bool {
	if o != nil && o.Division != nil {
		return true
	}

	return false
}

// SetDivision gets a reference to the given string and assigns it to the Division field.
func (o *SchemaDataDisclosedInnerRecipientsInner) SetDivision(v string) {
	o.Division = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *SchemaDataDisclosedInnerRecipientsInner) GetAddress() string {
	if o == nil || o.Address == nil {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaDataDisclosedInnerRecipientsInner) GetAddressOk() (*string, bool) {
	if o == nil || o.Address == nil {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *SchemaDataDisclosedInnerRecipientsInner) HasAddress() bool {
	if o != nil && o.Address != nil {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *SchemaDataDisclosedInnerRecipientsInner) SetAddress(v string) {
	o.Address = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *SchemaDataDisclosedInnerRecipientsInner) GetCountry() string {
	if o == nil || o.Country == nil {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaDataDisclosedInnerRecipientsInner) GetCountryOk() (*string, bool) {
	if o == nil || o.Country == nil {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *SchemaDataDisclosedInnerRecipientsInner) HasCountry() bool {
	if o != nil && o.Country != nil {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *SchemaDataDisclosedInnerRecipientsInner) SetCountry(v string) {
	o.Country = &v
}

// GetRepresentative returns the Representative field value if set, zero value otherwise.
func (o *SchemaDataDisclosedInnerRecipientsInner) GetRepresentative() SchemaDataDisclosedInnerRecipientsInnerRepresentative {
	if o == nil || o.Representative == nil {
		var ret SchemaDataDisclosedInnerRecipientsInnerRepresentative
		return ret
	}
	return *o.Representative
}

// GetRepresentativeOk returns a tuple with the Representative field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaDataDisclosedInnerRecipientsInner) GetRepresentativeOk() (*SchemaDataDisclosedInnerRecipientsInnerRepresentative, bool) {
	if o == nil || o.Representative == nil {
		return nil, false
	}
	return o.Representative, true
}

// HasRepresentative returns a boolean if a field has been set.
func (o *SchemaDataDisclosedInnerRecipientsInner) HasRepresentative() bool {
	if o != nil && o.Representative != nil {
		return true
	}

	return false
}

// SetRepresentative gets a reference to the given SchemaDataDisclosedInnerRecipientsInnerRepresentative and assigns it to the Representative field.
func (o *SchemaDataDisclosedInnerRecipientsInner) SetRepresentative(v SchemaDataDisclosedInnerRecipientsInnerRepresentative) {
	o.Representative = &v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *SchemaDataDisclosedInnerRecipientsInner) GetCategory() string {
	if o == nil || o.Category == nil {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaDataDisclosedInnerRecipientsInner) GetCategoryOk() (*string, bool) {
	if o == nil || o.Category == nil {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *SchemaDataDisclosedInnerRecipientsInner) HasCategory() bool {
	if o != nil && o.Category != nil {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *SchemaDataDisclosedInnerRecipientsInner) SetCategory(v string) {
	o.Category = &v
}

func (o SchemaDataDisclosedInnerRecipientsInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Division != nil {
		toSerialize["division"] = o.Division
	}
	if o.Address != nil {
		toSerialize["address"] = o.Address
	}
	if o.Country != nil {
		toSerialize["country"] = o.Country
	}
	if o.Representative != nil {
		toSerialize["representative"] = o.Representative
	}
	if o.Category != nil {
		toSerialize["category"] = o.Category
	}
	return json.Marshal(toSerialize)
}

type NullableSchemaDataDisclosedInnerRecipientsInner struct {
	value *SchemaDataDisclosedInnerRecipientsInner
	isSet bool
}

func (v NullableSchemaDataDisclosedInnerRecipientsInner) Get() *SchemaDataDisclosedInnerRecipientsInner {
	return v.value
}

func (v *NullableSchemaDataDisclosedInnerRecipientsInner) Set(val *SchemaDataDisclosedInnerRecipientsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSchemaDataDisclosedInnerRecipientsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSchemaDataDisclosedInnerRecipientsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSchemaDataDisclosedInnerRecipientsInner(val *SchemaDataDisclosedInnerRecipientsInner) *NullableSchemaDataDisclosedInnerRecipientsInner {
	return &NullableSchemaDataDisclosedInnerRecipientsInner{value: val, isSet: true}
}

func (v NullableSchemaDataDisclosedInnerRecipientsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSchemaDataDisclosedInnerRecipientsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


