/*
Kopfsachen

Kopfsachen e. V. is an association for the promotion of young people's mental health. The goal is to teach the basics of mental health literacy in various educational formats.

API version: 1.0.2
Contact: mail@kopfsachen.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// BrowserBaseFlowExample struct for BrowserBaseFlowExample
type BrowserBaseFlowExample struct {
}

// NewBrowserBaseFlowExample instantiates a new BrowserBaseFlowExample object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBrowserBaseFlowExample() *BrowserBaseFlowExample {
	this := BrowserBaseFlowExample{}
	return &this
}

// NewBrowserBaseFlowExampleWithDefaults instantiates a new BrowserBaseFlowExample object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBrowserBaseFlowExampleWithDefaults() *BrowserBaseFlowExample {
	this := BrowserBaseFlowExample{}
	return &this
}

func (o BrowserBaseFlowExample) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	return json.Marshal(toSerialize)
}

type NullableBrowserBaseFlowExample struct {
	value *BrowserBaseFlowExample
	isSet bool
}

func (v NullableBrowserBaseFlowExample) Get() *BrowserBaseFlowExample {
	return v.value
}

func (v *NullableBrowserBaseFlowExample) Set(val *BrowserBaseFlowExample) {
	v.value = val
	v.isSet = true
}

func (v NullableBrowserBaseFlowExample) IsSet() bool {
	return v.isSet
}

func (v *NullableBrowserBaseFlowExample) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBrowserBaseFlowExample(val *BrowserBaseFlowExample) *NullableBrowserBaseFlowExample {
	return &NullableBrowserBaseFlowExample{value: val, isSet: true}
}

func (v NullableBrowserBaseFlowExample) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBrowserBaseFlowExample) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


