/*
Kopfsachen

Kopfsachen e. V. is an association for the promotion of young people's mental health. The goal is to teach the basics of mental health literacy in various educational formats.

API version: 1.0.2
Contact: mail@kopfsachen.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// ApiRegistraionFlowExample struct for ApiRegistraionFlowExample
type ApiRegistraionFlowExample struct {
}

// NewApiRegistraionFlowExample instantiates a new ApiRegistraionFlowExample object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiRegistraionFlowExample() *ApiRegistraionFlowExample {
	this := ApiRegistraionFlowExample{}
	return &this
}

// NewApiRegistraionFlowExampleWithDefaults instantiates a new ApiRegistraionFlowExample object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiRegistraionFlowExampleWithDefaults() *ApiRegistraionFlowExample {
	this := ApiRegistraionFlowExample{}
	return &this
}

func (o ApiRegistraionFlowExample) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	return json.Marshal(toSerialize)
}

type NullableApiRegistraionFlowExample struct {
	value *ApiRegistraionFlowExample
	isSet bool
}

func (v NullableApiRegistraionFlowExample) Get() *ApiRegistraionFlowExample {
	return v.value
}

func (v *NullableApiRegistraionFlowExample) Set(val *ApiRegistraionFlowExample) {
	v.value = val
	v.isSet = true
}

func (v NullableApiRegistraionFlowExample) IsSet() bool {
	return v.isSet
}

func (v *NullableApiRegistraionFlowExample) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiRegistraionFlowExample(val *ApiRegistraionFlowExample) *NullableApiRegistraionFlowExample {
	return &NullableApiRegistraionFlowExample{value: val, isSet: true}
}

func (v NullableApiRegistraionFlowExample) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiRegistraionFlowExample) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


