/*
Kopfsachen

Kopfsachen e. V. is an association for the promotion of young people's mental health. The goal is to teach the basics of mental health literacy in various educational formats.

API version: 0.2
Contact: mail@kopfsachen.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// GetMotivatorUserId200ResponseInner struct for GetMotivatorUserId200ResponseInner
type GetMotivatorUserId200ResponseInner struct {
	Id *string `json:"id,omitempty"`
	Type *string `json:"type,omitempty"`
	Headline *string `json:"headline,omitempty"`
	Description *string `json:"description,omitempty"`
	TextContents []string `json:"textContents,omitempty"`
	MediaContents []MotivatorMediaContentsInner `json:"mediaContents,omitempty"`
	// May describe a form for input by the user (format to be defined, e.g., JSON Schema).
	UserInputForm *string `json:"userInputForm,omitempty"`
	MotivatorId *string `json:"motivatorId,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
	Results []string `json:"results,omitempty"`
}

// NewGetMotivatorUserId200ResponseInner instantiates a new GetMotivatorUserId200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMotivatorUserId200ResponseInner() *GetMotivatorUserId200ResponseInner {
	this := GetMotivatorUserId200ResponseInner{}
	return &this
}

// NewGetMotivatorUserId200ResponseInnerWithDefaults instantiates a new GetMotivatorUserId200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMotivatorUserId200ResponseInnerWithDefaults() *GetMotivatorUserId200ResponseInner {
	this := GetMotivatorUserId200ResponseInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetMotivatorUserId200ResponseInner) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMotivatorUserId200ResponseInner) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetMotivatorUserId200ResponseInner) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GetMotivatorUserId200ResponseInner) SetId(v string) {
	o.Id = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GetMotivatorUserId200ResponseInner) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMotivatorUserId200ResponseInner) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetMotivatorUserId200ResponseInner) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GetMotivatorUserId200ResponseInner) SetType(v string) {
	o.Type = &v
}

// GetHeadline returns the Headline field value if set, zero value otherwise.
func (o *GetMotivatorUserId200ResponseInner) GetHeadline() string {
	if o == nil || o.Headline == nil {
		var ret string
		return ret
	}
	return *o.Headline
}

// GetHeadlineOk returns a tuple with the Headline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMotivatorUserId200ResponseInner) GetHeadlineOk() (*string, bool) {
	if o == nil || o.Headline == nil {
		return nil, false
	}
	return o.Headline, true
}

// HasHeadline returns a boolean if a field has been set.
func (o *GetMotivatorUserId200ResponseInner) HasHeadline() bool {
	if o != nil && o.Headline != nil {
		return true
	}

	return false
}

// SetHeadline gets a reference to the given string and assigns it to the Headline field.
func (o *GetMotivatorUserId200ResponseInner) SetHeadline(v string) {
	o.Headline = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *GetMotivatorUserId200ResponseInner) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMotivatorUserId200ResponseInner) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *GetMotivatorUserId200ResponseInner) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *GetMotivatorUserId200ResponseInner) SetDescription(v string) {
	o.Description = &v
}

// GetTextContents returns the TextContents field value if set, zero value otherwise.
func (o *GetMotivatorUserId200ResponseInner) GetTextContents() []string {
	if o == nil || o.TextContents == nil {
		var ret []string
		return ret
	}
	return o.TextContents
}

// GetTextContentsOk returns a tuple with the TextContents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMotivatorUserId200ResponseInner) GetTextContentsOk() ([]string, bool) {
	if o == nil || o.TextContents == nil {
		return nil, false
	}
	return o.TextContents, true
}

// HasTextContents returns a boolean if a field has been set.
func (o *GetMotivatorUserId200ResponseInner) HasTextContents() bool {
	if o != nil && o.TextContents != nil {
		return true
	}

	return false
}

// SetTextContents gets a reference to the given []string and assigns it to the TextContents field.
func (o *GetMotivatorUserId200ResponseInner) SetTextContents(v []string) {
	o.TextContents = v
}

// GetMediaContents returns the MediaContents field value if set, zero value otherwise.
func (o *GetMotivatorUserId200ResponseInner) GetMediaContents() []MotivatorMediaContentsInner {
	if o == nil || o.MediaContents == nil {
		var ret []MotivatorMediaContentsInner
		return ret
	}
	return o.MediaContents
}

// GetMediaContentsOk returns a tuple with the MediaContents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMotivatorUserId200ResponseInner) GetMediaContentsOk() ([]MotivatorMediaContentsInner, bool) {
	if o == nil || o.MediaContents == nil {
		return nil, false
	}
	return o.MediaContents, true
}

// HasMediaContents returns a boolean if a field has been set.
func (o *GetMotivatorUserId200ResponseInner) HasMediaContents() bool {
	if o != nil && o.MediaContents != nil {
		return true
	}

	return false
}

// SetMediaContents gets a reference to the given []MotivatorMediaContentsInner and assigns it to the MediaContents field.
func (o *GetMotivatorUserId200ResponseInner) SetMediaContents(v []MotivatorMediaContentsInner) {
	o.MediaContents = v
}

// GetUserInputForm returns the UserInputForm field value if set, zero value otherwise.
func (o *GetMotivatorUserId200ResponseInner) GetUserInputForm() string {
	if o == nil || o.UserInputForm == nil {
		var ret string
		return ret
	}
	return *o.UserInputForm
}

// GetUserInputFormOk returns a tuple with the UserInputForm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMotivatorUserId200ResponseInner) GetUserInputFormOk() (*string, bool) {
	if o == nil || o.UserInputForm == nil {
		return nil, false
	}
	return o.UserInputForm, true
}

// HasUserInputForm returns a boolean if a field has been set.
func (o *GetMotivatorUserId200ResponseInner) HasUserInputForm() bool {
	if o != nil && o.UserInputForm != nil {
		return true
	}

	return false
}

// SetUserInputForm gets a reference to the given string and assigns it to the UserInputForm field.
func (o *GetMotivatorUserId200ResponseInner) SetUserInputForm(v string) {
	o.UserInputForm = &v
}

// GetMotivatorId returns the MotivatorId field value if set, zero value otherwise.
func (o *GetMotivatorUserId200ResponseInner) GetMotivatorId() string {
	if o == nil || o.MotivatorId == nil {
		var ret string
		return ret
	}
	return *o.MotivatorId
}

// GetMotivatorIdOk returns a tuple with the MotivatorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMotivatorUserId200ResponseInner) GetMotivatorIdOk() (*string, bool) {
	if o == nil || o.MotivatorId == nil {
		return nil, false
	}
	return o.MotivatorId, true
}

// HasMotivatorId returns a boolean if a field has been set.
func (o *GetMotivatorUserId200ResponseInner) HasMotivatorId() bool {
	if o != nil && o.MotivatorId != nil {
		return true
	}

	return false
}

// SetMotivatorId gets a reference to the given string and assigns it to the MotivatorId field.
func (o *GetMotivatorUserId200ResponseInner) SetMotivatorId(v string) {
	o.MotivatorId = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *GetMotivatorUserId200ResponseInner) GetTimestamp() time.Time {
	if o == nil || o.Timestamp == nil {
		var ret time.Time
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMotivatorUserId200ResponseInner) GetTimestampOk() (*time.Time, bool) {
	if o == nil || o.Timestamp == nil {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *GetMotivatorUserId200ResponseInner) HasTimestamp() bool {
	if o != nil && o.Timestamp != nil {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given time.Time and assigns it to the Timestamp field.
func (o *GetMotivatorUserId200ResponseInner) SetTimestamp(v time.Time) {
	o.Timestamp = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *GetMotivatorUserId200ResponseInner) GetResults() []string {
	if o == nil || o.Results == nil {
		var ret []string
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMotivatorUserId200ResponseInner) GetResultsOk() ([]string, bool) {
	if o == nil || o.Results == nil {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *GetMotivatorUserId200ResponseInner) HasResults() bool {
	if o != nil && o.Results != nil {
		return true
	}

	return false
}

// SetResults gets a reference to the given []string and assigns it to the Results field.
func (o *GetMotivatorUserId200ResponseInner) SetResults(v []string) {
	o.Results = v
}

func (o GetMotivatorUserId200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Headline != nil {
		toSerialize["headline"] = o.Headline
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.TextContents != nil {
		toSerialize["textContents"] = o.TextContents
	}
	if o.MediaContents != nil {
		toSerialize["mediaContents"] = o.MediaContents
	}
	if o.UserInputForm != nil {
		toSerialize["userInputForm"] = o.UserInputForm
	}
	if o.MotivatorId != nil {
		toSerialize["motivatorId"] = o.MotivatorId
	}
	if o.Timestamp != nil {
		toSerialize["timestamp"] = o.Timestamp
	}
	if o.Results != nil {
		toSerialize["results"] = o.Results
	}
	return json.Marshal(toSerialize)
}

type NullableGetMotivatorUserId200ResponseInner struct {
	value *GetMotivatorUserId200ResponseInner
	isSet bool
}

func (v NullableGetMotivatorUserId200ResponseInner) Get() *GetMotivatorUserId200ResponseInner {
	return v.value
}

func (v *NullableGetMotivatorUserId200ResponseInner) Set(val *GetMotivatorUserId200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMotivatorUserId200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMotivatorUserId200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMotivatorUserId200ResponseInner(val *GetMotivatorUserId200ResponseInner) *NullableGetMotivatorUserId200ResponseInner {
	return &NullableGetMotivatorUserId200ResponseInner{value: val, isSet: true}
}

func (v NullableGetMotivatorUserId200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMotivatorUserId200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


