/*
Kopfsachen

Kopfsachen e. V. is an association for the promotion of young people's mental health. The goal is to teach the basics of mental health literacy in various educational formats.

API version: 0.2
Contact: mail@kopfsachen.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// Motivator struct for Motivator
type Motivator struct {
	Id *string `json:"id,omitempty"`
	Type *string `json:"type,omitempty"`
	Headline *string `json:"headline,omitempty"`
	Description *string `json:"description,omitempty"`
	TextContents []string `json:"textContents,omitempty"`
	MediaContents []MotivatorMediaContentsInner `json:"mediaContents,omitempty"`
	// May describe a form for input by the user (format to be defined, e.g., JSON Schema).
	UserInputForm *string `json:"userInputForm,omitempty"`
}

// NewMotivator instantiates a new Motivator object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMotivator() *Motivator {
	this := Motivator{}
	return &this
}

// NewMotivatorWithDefaults instantiates a new Motivator object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMotivatorWithDefaults() *Motivator {
	this := Motivator{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Motivator) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Motivator) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Motivator) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Motivator) SetId(v string) {
	o.Id = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *Motivator) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Motivator) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *Motivator) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *Motivator) SetType(v string) {
	o.Type = &v
}

// GetHeadline returns the Headline field value if set, zero value otherwise.
func (o *Motivator) GetHeadline() string {
	if o == nil || o.Headline == nil {
		var ret string
		return ret
	}
	return *o.Headline
}

// GetHeadlineOk returns a tuple with the Headline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Motivator) GetHeadlineOk() (*string, bool) {
	if o == nil || o.Headline == nil {
		return nil, false
	}
	return o.Headline, true
}

// HasHeadline returns a boolean if a field has been set.
func (o *Motivator) HasHeadline() bool {
	if o != nil && o.Headline != nil {
		return true
	}

	return false
}

// SetHeadline gets a reference to the given string and assigns it to the Headline field.
func (o *Motivator) SetHeadline(v string) {
	o.Headline = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Motivator) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Motivator) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Motivator) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Motivator) SetDescription(v string) {
	o.Description = &v
}

// GetTextContents returns the TextContents field value if set, zero value otherwise.
func (o *Motivator) GetTextContents() []string {
	if o == nil || o.TextContents == nil {
		var ret []string
		return ret
	}
	return o.TextContents
}

// GetTextContentsOk returns a tuple with the TextContents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Motivator) GetTextContentsOk() ([]string, bool) {
	if o == nil || o.TextContents == nil {
		return nil, false
	}
	return o.TextContents, true
}

// HasTextContents returns a boolean if a field has been set.
func (o *Motivator) HasTextContents() bool {
	if o != nil && o.TextContents != nil {
		return true
	}

	return false
}

// SetTextContents gets a reference to the given []string and assigns it to the TextContents field.
func (o *Motivator) SetTextContents(v []string) {
	o.TextContents = v
}

// GetMediaContents returns the MediaContents field value if set, zero value otherwise.
func (o *Motivator) GetMediaContents() []MotivatorMediaContentsInner {
	if o == nil || o.MediaContents == nil {
		var ret []MotivatorMediaContentsInner
		return ret
	}
	return o.MediaContents
}

// GetMediaContentsOk returns a tuple with the MediaContents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Motivator) GetMediaContentsOk() ([]MotivatorMediaContentsInner, bool) {
	if o == nil || o.MediaContents == nil {
		return nil, false
	}
	return o.MediaContents, true
}

// HasMediaContents returns a boolean if a field has been set.
func (o *Motivator) HasMediaContents() bool {
	if o != nil && o.MediaContents != nil {
		return true
	}

	return false
}

// SetMediaContents gets a reference to the given []MotivatorMediaContentsInner and assigns it to the MediaContents field.
func (o *Motivator) SetMediaContents(v []MotivatorMediaContentsInner) {
	o.MediaContents = v
}

// GetUserInputForm returns the UserInputForm field value if set, zero value otherwise.
func (o *Motivator) GetUserInputForm() string {
	if o == nil || o.UserInputForm == nil {
		var ret string
		return ret
	}
	return *o.UserInputForm
}

// GetUserInputFormOk returns a tuple with the UserInputForm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Motivator) GetUserInputFormOk() (*string, bool) {
	if o == nil || o.UserInputForm == nil {
		return nil, false
	}
	return o.UserInputForm, true
}

// HasUserInputForm returns a boolean if a field has been set.
func (o *Motivator) HasUserInputForm() bool {
	if o != nil && o.UserInputForm != nil {
		return true
	}

	return false
}

// SetUserInputForm gets a reference to the given string and assigns it to the UserInputForm field.
func (o *Motivator) SetUserInputForm(v string) {
	o.UserInputForm = &v
}

func (o Motivator) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Headline != nil {
		toSerialize["headline"] = o.Headline
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.TextContents != nil {
		toSerialize["textContents"] = o.TextContents
	}
	if o.MediaContents != nil {
		toSerialize["mediaContents"] = o.MediaContents
	}
	if o.UserInputForm != nil {
		toSerialize["userInputForm"] = o.UserInputForm
	}
	return json.Marshal(toSerialize)
}

type NullableMotivator struct {
	value *Motivator
	isSet bool
}

func (v NullableMotivator) Get() *Motivator {
	return v.value
}

func (v *NullableMotivator) Set(val *Motivator) {
	v.value = val
	v.isSet = true
}

func (v NullableMotivator) IsSet() bool {
	return v.isSet
}

func (v *NullableMotivator) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMotivator(val *Motivator) *NullableMotivator {
	return &NullableMotivator{value: val, isSet: true}
}

func (v NullableMotivator) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMotivator) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


